"""empty message

Revision ID: 0d34bba9185b
Revises: fc2aff5bc180
Create Date: 2020-06-02 11:45:18.782085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d34bba9185b'
down_revision = 'fc2aff5bc180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('highlight_post', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlight_post', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
