"""empty message

Revision ID: 7e50705cac3d
Revises: 257a4bf5cb8c
Create Date: 2020-06-07 19:00:39.731409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e50705cac3d'
down_revision = '257a4bf5cb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('read_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'read_count')
    # ### end Alembic commands ###
