"""empty message

Revision ID: 83300a331045
Revises: 0d34bba9185b
Create Date: 2020-06-02 14:48:55.610622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83300a331045'
down_revision = '0d34bba9185b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlight_post', sa.Column('name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('highlight_post', 'name')
    # ### end Alembic commands ###
