"""empty message

Revision ID: a2687e490bcd
Revises: 45f156398fa8
Create Date: 2020-06-02 14:55:10.909506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2687e490bcd'
down_revision = '45f156398fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlight_post', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'highlight_post', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'highlight_post', type_='foreignkey')
    op.drop_column('highlight_post', 'post_id')
    # ### end Alembic commands ###
