"""empty message

Revision ID: fc2aff5bc180
Revises: 7d21a12f78a1
Create Date: 2020-06-02 11:20:39.068941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2aff5bc180'
down_revision = '7d21a12f78a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlight_post', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'highlight_post', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'highlight_post', type_='foreignkey')
    op.drop_column('highlight_post', 'post_id')
    # ### end Alembic commands ###
